### ISSUE TITLE
不显示发音

### ISSUE THREAD

**Issue by NoverNobida** [Crissium/SilverDict#18]
相当多的词典（例如[这个](https://forum.freemdict.com/t/topic/9947)）的单词发音不显示，取而代之的是一个很长的进度条，严重影响使用。
![图片](https://github.com/user-attachments/assets/50bf9df5-ed62-4adc-be06-73802f2513fa)

**Comment by Crissium** [comment]
这个看起来是发音文件提取失败了，有进度条是“正常”的，不过显示进度条可能从用户体验的角度不太好。

我需要仔细研究一下这个词典，其他词典发音可以播放吗？

**Comment by NoverNobida** [comment]
可能我没表述清楚，我的意思不是不发声音，是单词没有音标，例如图中的bad,按理后面就是 `/bæd/` ，但是这个却没有，其他部分词典也是。
对于进度条，是否可考虑有选项去关闭。

**Comment by Crissium** [comment]
我刚刚 push 了一个 commit 修复了这个词典，错误原因看起在于它引用了并不存在的音频文件。我不确定其他词典的问题是否可以解决。

![image](https://github.com/user-attachments/assets/a37ca104-24d9-45b2-b204-fc6a0d69d31b)

进度条是 HTML5 audio 自带的，我目前只知道如何在 Chrome 上控制其中各种部件的 style, 其他浏览器需要研究。

**Comment by NoverNobida** [comment]
问题已得到解决！
