### ISSUE TITLE
Collaboration on this project?

### ISSUE THREAD

**Issue by jiang-qian** [Crissium/SilverDict#2]
Hi there, I found this project when searching for an alternative of Goldendict, since it no longer works on newer version of Android. 

I have always wanted to have a commandline dictionary look up tool for stardict and ABBYY DSL dictionary format, with a web based front end, so that it would be extremely portable and easy to maintain. For example, I envision using this on Android on Termux, running a local browser and accessing the dictionary interface on a local browser. This way none of those scope storage troubles or any future API changes would destroy the function of the the app.

I myself is not a real programmer (I only code for my scientific work, in C and Fortran, mostly numerical works run on large clusters). But I have started collaborating with two experienced programmers and we made some progress in achieving this goal. 

One result is this project https://github.com/proteusx/lectus But it has since stalled because the programmer in question prefer perl, and is not very well versed in the web interface side. Nonetheless, that project achieved much success in producing a commandline parser for DSL format and converting all its tags (e.g. colors) into html and can be displayed in a rudimentary web interface. The DSL dictionary is also indexed in sqlite database, with excellent search performance.

I also kept a decade-long correspondence with the developer of this project
https://www.lesbonscomptes.com/recoll/pages/index-recoll.html
And he has kindly coded, in python, two very modular searching and indexing code, which can index the dictionaries, in both stardict and DSL format, in a sqlite database, and can search and retrieve the raw entries with excellent performance. (in a few tenths of seconds on Android phone via termux even for lexicon with million entries, and scaling well with number of entries).

Given your expertise in web development, I see a possible synergy in putting what my two friends already achieved into your project and reaching our shared goal a lot more quickly.

If you're interested in collaborating, perhaps we could get in touch by email. My email address is just like my github username, but instead of the dash in between my first and last name there is a dot, and the email domain name is gmail. Please reach out to me and I can send you my second friend's python modules to index the DSL and stardict format into an sqlite databse and we can see what's the best way to proceed.

**Comment by Crissium** [comment]
Hello! I sent a message with my school e-mail. It could be blocked though. So if you do not hear from me, I will send it again with my personal Gmail.

**Comment by jiang-qian** [comment]
I got your email from you school address! I will reply it in details but I do prefer to send message to your personal Gmail if that's possible. Could you please send me an email from your personal Gmail address, too? Thank you and I look forward to our collaboration as well as trying out your code on termux as well!

**Comment by jiang-qian** [comment]
If I hit any snag using your code on Termux, should I file a bug report here or reaching out to you by email first?

**Comment by Crissium** [comment]
Closes as StarDict and DSL have been supported!
