### ISSUE TITLE
Failure to set up on Android and Termux

### ISSUE THREAD

**Issue by jiang-qian** [Crissium/SilverDict#4]
System is Android 13 on Google Pixel 6 Pro. Attempted step
on Termux:
pip3 install flask
pip3 install fask-cors
pip3 install waitress
pip3 install requests
apt install yarn

scp the zip file downloaded from github to termux, unzip it and enter the directory
cd client
yarn install
yarn build
mv dict ../http_server
cd ../
python 3.11 http_server/http_server.py
python 3.11 server/server.py

open web browser, nothing happens
on the server/server.py terminal no output
on http_server terminal
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 44442)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.11/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/data/com.termux/files/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/data/data/com.termux/files/usr/lib/python3.11/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/data/data/com.termux/files/usr/lib/python3.11/http/server.py", line 424, in handle_one_request
    method()
  File "/data/data/com.termux/files/home/SilverDict-main/http_server/http_server.py", line 26, in do_GET
    with open('dist' + path, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dist/index.html'
----------------------------------------
127.0.0.1 - - [28/Aug/2023 03:55:15] "GET /favicon.ico HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 44450)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.11/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/data/com.termux/files/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/data/data/com.termux/files/usr/lib/python3.11/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/data/data/com.termux/files/usr/lib/python3.11/http/server.py", line 424, in handle_one_request
    method()
  File "/data/data/com.termux/files/home/SilverDict-main/http_server/http_server.py", line 26, in do_GET
    with open('dist' + path, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dist/favicon.ico'
----------------------------------------
  
Any help in getting it to work would be most appreciated!

**Comment by Crissium** [comment]
First of all, I do not advise build the static files (HTML, CSS, JS) in Android. You can simply copy the `dist` directory built on the desktop.

And again, check this out: https://github.com/Crissium/SilverDict/issues/3#issuecomment-1695209995

Besides, if your mobile device and desktop are in the same network, you can simply allow access to the server on your desktop by changing the listening address from `localhost` to `0.0.0.0`, and opening the ports (80/8081 & 2628) with `firewall-cmd` or something. This avoids unnecessary duplication.

**Comment by jiang-qian** [comment]
Yes, going to the directory of the http_server works for mobile as well!

I would argue that mobile is probably more of a priority for many users. Dictionaries are especially useful on devices, since you can carry it everywhere. I know for example that many classicists and archaeologists who need to go to remote places for field works and when they encounter inscriptions, a mobile device, not a laptop and certainly not paper dictionaries, is often the only thing they have at hand, and  offline dictionaries are necessary since they often have no internet access.

Right now they rely on goldendict, but with Android's enforcement of scooped storage, we're having great trouble getting it installed on newer phones! Recently I tried to get goldendict to work for a friend going to the remote field and couldn't get it to work on his new Android phone!

Even for me, as someone who loves reading in Ancient Greek (and a little Latin), most of my readings are in printed books (or scanned PDF on an ereader), and while working on them having a phone at hand instead of a computer is so much more convenient!

It would be wonderful if an app could work, but I am concerned that an app would becomes unusable when platform owner like Google change the API requirements and access rules. A termux based server serving mobile friendly webpages would be much more flexible and less subject to the whim of the platform API changes, I assume, though a mobile app would probably help many of the field classicists and archaeologists uncomfortable with command line

Thank you again for working on this very valuable project!

**Comment by jiang-qian** [comment]
How to add dictionary to the Android web version? I scp the mdx file to the home directory of Termux but could not find the right "Path on the server" when choosing the file.

By the way, once I put the browser in the landscape mode, the current three column formats looks ok. Perhaps putting them into one column format would make it more mobile friendly? We don't have to have dictionaries list all the time nor the setting column on the right. Like in Goldendict, such options could be added perhaps with a dropdown menu, perhaps?

On the small mobile screen the space is at a premium, so perhaps it is easier to simply display the search bar and results so that one can maximize the amount of information on a single screen without scrolling?

**Comment by Crissium** [comment]
If your dictionary is located on a SD card (i.e. external storage), the path should be something like `/storage/emulated/0/mdict/doc/dict.mdx` (Google 'termux external storage setup' if you haven't done so). If it is in the home directory of Termux then the path is perhaps `/data/data/com.termux/files/home` (I haven't tested). (Pro tip: try `pwd`)

When I was designing the web page, I did not even envisage using it on a mobile device, because, well, GoldenDict still works, however imperfectly, after I upgraded to Android 12. Therefore, I should design a mobile-oriented web page from scratch and the existing front-end code cannot be reused.

And, worry not, because the mobile app I am working on is developed with Flutter, which should be easily compiled into a web app. As for field classicists and archaeologists, setting up the server locally on Android could be quite a challenge. But I could see no way to make this process more user-friendly.

**Comment by jiang-qian** [comment]
I did use pwd and tried to type the address, but I must have typed it wrong. It is hard to type long directory names on the tiny screen! Now I carefully typed it again and it works!

My concern is portability. Ideally the Android version can work offline once set up, with no internet connection needed. Once you have any app and has to be installed, you are at the mercy of Google. I upgraded to Android 13 and Goldendict still works. However, I have a friend who bought an Android 13 phone, and I could not get Goldendict to install on his phone at all! Android 14 would only gets worse...

For command line interface, once everything works, I can write a shell script to automate the installation process for my classicist and archaeologist friends. That should make everything much more user friendly.

About Flutter, would that introduce more dependency? I was very concerned that things like Vue and Flutter would make the code base less portable. For example, I was even able to get lectus (my friend's perl based lexicon) to run on my router running OpenWrt! (This way everyone on my home network can look up words on it without having to install it.) That might be extreme, but at the very minimal it should be easily installable on termux with pip3 and apt, which your app currently does!

Again, I am writing you an email about the python code that index and parse DSL and stardict. I hope this could be integrated into your code without too much trouble!

**Comment by Crissium** [comment]
> It is hard to type long directory names on the tiny screen

It is indeed challenging to type long paths, but for security reasons I cannot let users do things like browsing the entire filesystem.

> I can write a shell script to automate the installation process for my classicist and archaeologist friends

That's a good idea. Try feeding the dictionary list to the server with curl:

```bash
curl -X POST -d '{"dictionary_display_name": "Le Grand Robert", "dictionary_name": "GrandRobert", "dictionary_format": "MDict (.mdx)", "dictionary_filename": "/backend/dicts/GrandRobert.mdx"}' http://localhost/api/metadata/dictionary_list -H "Content-Type: application/json"
```

> I was even able to get lectus (my friend's perl based lexicon) to run on my router running OpenWrt!

You can also do this with SilverDict :) Once set up, it will be accessible to everyone in the local network.

> I was very concerned that things like Vue and Flutter would make the code base less portable.

Flutter _is_ portable. An app developed with Flutter runs natively on the web, Android, and iOS, and has support for Linux (with GTK+).

By the way, a command-line tool is not an 'app' in the generally perceived sense. An app is something that you install from an app store and has compartmentalised storage and a user-friendly GUI.

**Comment by jiang-qian** [comment]
I know little about Flutter, as you can see from my comments about it! I do know that Android and iOS has progressively restricted permission and changed their API over the past decade or so, and many programs become abandonware as a consequence. It is a devil's bargain that we have to run our most physically portable device under an API controlled by two giant corporations! If an app has to be distributed on an app store, it is subject to their caprice. 

I'm very ignorant about this: with scoped storage, how will a Flutter based app install dictionaries? Just as SilverDict does today?

Thus, even just as a backup solution, it would be great, apart from any app, to have a server, much like SilverDict does today, run on Termux (which seems to be pretty stable for quite a number of years by now) and serve up a locally a web interface that is mobile friendly...

Maybe I'm paranoid. I started using stardict dictionaries on Android with ColorDict more than a decade ago and the moved to GoldenDict and even paid for it (for myself and a friend). My reading set up in Greek and Latin has been so intertwined with my dictionaries and encyclopedias that I dread very much a future where one cannot access stardict/DSL dictionary format on a mobile device!

I know about mdx format, which seems to be still supported on Android but can one convert DSL and stardict into that format? Pyglossary can read any format and convert them into stardict, but not mdx....  So many dictionaries are in DSL and stardict format...

I'm going back to write that email to you!

**Comment by Crissium** [comment]
SilverDict follows the client-server architecture, comprising two components, the Client, and the Server. The Server sees and manipulates the dictionary files, while the Client cannot, but sends requests to the Server, which responds with definitions, among others. The two components can run in separate machines so long as the firewall is properly configured.

For example, find the line that defines `SERVER_URL` in `/client/src/App.vue`, comment out the line that contains localhost and uncomment the other, rerun `yarn build`, and now you are using my demo server. Try it.

In this way, unlike GoldenDict, a server can serve as many clients as possible without any redundancy. Here I have traded speed for space.

Additionally, you can put the HTML, CSS and JS files on the same server (a machine, not the software), so that anyone with access to the server do not even need to have the Client installed on their local machines. That's what I am doing with the live demo.

**Comment by Crissium** [comment]
Yes, I forgot to mention, the Flutter app would fill the role of the Client, as the current Vue-based web app does. It should certainly work with a Server that runs locally.

And I have received your email and will start working on it immediately.
